"""Self-contained HTML player generator (PRD.md §5.6)."""

from __future__ import annotations

import html
import json

from termify.engine import FrameSequence
from termify.ansi_to_html import ansi_to_html


_PLAYER_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>Termify — {charset} animation</title>
<style>
  :root {{ --bg:#0a0e14; --fg:#c9d1d9; --accent:#58a6ff; }}
  body {{ margin:0; background:var(--bg); color:var(--fg);
          font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
          display:flex; flex-direction:column; align-items:center;
          min-height:100vh; padding:24px; box-sizing:border-box; }}
  h1 {{ font-size:14px; font-weight:600; letter-spacing:.05em; color:var(--accent); }}
  .container {{ display:flex; flex-direction:column; align-items:center; max-width:100%; }}
  pre {{ background:#161b22; border:1px solid #30363d; border-radius:8px;
        padding:16px 20px; line-height:1.3; font-size:13px;
        overflow:hidden; white-space:pre; margin:0; }}
  canvas {{ image-rendering:pixelated; image-rendering:crisp-edges;
           background:#000; border-radius:4px; }}
  .controls {{ margin-top:12px; display:none; align-items:center; gap:10px; }}
  .controls button {{ background:#161b22; color:var(--accent);
        border:1px solid #30363d; border-radius:6px; padding:6px 18px;
        font:inherit; cursor:pointer; }}
  .controls button:hover {{ border-color:var(--accent); }}
  .controls .hint {{ font-size:11px; color:#6e7681; }}
  footer {{ margin-top:12px; font-size:11px; color:#6e7681; }}
</style>
</head>
<body>
  <h1>Termify · {charset} · {w}×{h} · {n} frames</h1>
  <div class="container">
    <pre id="screen" style="{pre_style}"></pre>
    <canvas id="cv" style="{canvas_style}"></canvas>
    <div class="controls" id="controls">
      <button id="playBtn" type="button">▶ 播放</button>
      <span class="hint">含音频 · 浏览器要求点击后才开始播放</span>
    </div>
  </div>
  <footer>Generated by Termify — no external dependencies.</footer>
  <script>
    var FRAMES = {frames};
    var INTERVAL = {interval} * 1000;
    var IS_BLOCKS = {is_blocks};
    var AUDIO_URI = {audio_uri};
    var AUDIO_MIME = {audio_mime};
    var W = {w}, H = {h};
    var idx = 0;
    var el = document.getElementById('screen');
    var cv = document.getElementById('cv');
    var ctx = cv.getContext('2d');
    var audio = null;
    var timer = null;

    function fitTerminalFontSize() {{
      if (IS_BLOCKS) return;
      var container = el.parentElement;
      var availW = Math.min(960, window.innerWidth - 80);
      var availH = window.innerHeight * 0.75;
      var charRatio = 0.6;
      var lineHeightRatio = 1.3;
      var fsW = availW / (W * charRatio);
      var fsH = availH / (H * lineHeightRatio);
      var fs = Math.max(4, Math.min(Math.min(fsW, fsH), 24));
      el.style.fontSize = fs + 'px';
      el.style.lineHeight = lineHeightRatio;
    }}

    function parseBlocksFrame(frameStr) {{
      var lines = frameStr.split('\\n');
      var pixels = [];
      for (var li = 0; li < lines.length; li++) {{
        var line = lines[li];
        var toks = line.split(/(\\x1b\\[[0-9;]*m)/g);
        var fg = null, bg = null;
        for (var i = 0; i < toks.length; i++) {{
          var t = toks[i]; if (!t) continue;
          if (/^\\x1b\\[[0-9;]*m$/.test(t)) {{
            var inner = t.slice(2, -1);
            if (inner === '0') {{ fg = null; bg = null; }}
            else if (inner.indexOf('38;2;') === 0) {{
              var p = inner.split(';'); fg = [parseInt(p[2]),parseInt(p[3]),parseInt(p[4])];
            }} else if (inner.indexOf('48;2;') === 0) {{
              var p = inner.split(';'); bg = [parseInt(p[2]),parseInt(p[3]),parseInt(p[4])];
            }}
            continue;
          }}
          for (var j = 0; j < t.length; j++) {{
            if (t.charCodeAt(j) === 0x2580)
              pixels.push({{ top: fg||[0,0,0], bot: bg||[0,0,0] }});
          }}
        }}
      }}
      return pixels;
    }}

    function renderBlocks(frameIdx) {{
      var pixels = parseBlocksFrame(FRAMES[frameIdx]);
      if (!pixels.length) return;
      var cols = W, rows = pixels.length / cols;
      var baseW = Math.min(960, window.innerWidth - 80);
      var cellW = Math.max(2, Math.floor(baseW / cols));
      var cellH = cellW * 2;
      var canvasW = cols * cellW, canvasH = rows * cellH;
      if (cv.width !== canvasW || cv.height !== canvasH) {{
        cv.width = canvasW; cv.height = canvasH;
        cv.style.width = canvasW + 'px'; cv.style.height = canvasH + 'px';
      }}
      ctx.fillStyle = '#000';
      ctx.fillRect(0, 0, canvasW, canvasH);
      var halfH = cellH / 2;
      for (var i = 0; i < pixels.length; i++) {{
        var col = i % cols, row = Math.floor(i / cols);
        var x = col * cellW, y = row * cellH;
        var p = pixels[i];
        ctx.fillStyle = 'rgb('+p.top[0]+','+p.top[1]+','+p.top[2]+')';
        ctx.fillRect(x, y, cellW, halfH);
        ctx.fillStyle = 'rgb('+p.bot[0]+','+p.bot[1]+','+p.bot[2]+')';
        ctx.fillRect(x, y + halfH, cellW, halfH);
      }}
    }}

    function drawFrame(frameIdx) {{
      if (IS_BLOCKS) {{
        renderBlocks(frameIdx);
      }} else {{
        el.innerHTML = FRAMES[frameIdx];
      }}
    }}

    function tick() {{
      if (audio) {{
        // 音频为主时钟：帧位置跟随 audio.currentTime
        var sec = audio.currentTime % (FRAMES.length * INTERVAL / 1000);
        idx = Math.floor(sec / (INTERVAL / 1000)) % FRAMES.length;
      }} else {{
        idx = (idx + 1) % FRAMES.length;
      }}
      drawFrame(idx);
    }}

    function startLoop() {{
      if (timer === null) timer = setInterval(tick, INTERVAL);
    }}
    function stopLoop() {{
      if (timer !== null) {{ clearInterval(timer); timer = null; }}
    }}

    if (AUDIO_URI) {{
      // 自带音轨：浏览器自动播放策略要求用户手势，给出播放按钮
      audio = new Audio(AUDIO_URI);
      audio.loop = true;
      var controls = document.getElementById('controls');
      var playBtn = document.getElementById('playBtn');
      controls.style.display = 'flex';
      playBtn.addEventListener('click', function () {{
        if (audio.paused) {{
          audio.play();
          playBtn.textContent = '⏸ 暂停';
          startLoop();
        }} else {{
          audio.pause();
          playBtn.textContent = '▶ 播放';
          stopLoop();
        }}
      }});
      drawFrame(0);
    }} else {{
      fitTerminalFontSize();
      window.addEventListener('resize', fitTerminalFontSize);
      tick();
      setInterval(tick, INTERVAL);
    }}
  </script>
</body>
</html>
"""


def render(sequence: FrameSequence, audio_b64: str | None = None,
           audio_mime: str | None = None) -> str:
    """Generate a self-contained .html player page as a string.

    When ``audio_b64`` is given the page embeds that track (data URI) and
    plays it in sync with the frames (user-gesture gated per autoplay
    policy).
    """
    is_blocks = sequence.charset == "blocks"

    if is_blocks:
        # Blocks mode: one string per frame (raw ANSI, lines joined with \n);
        # JS splits it back and renders via <canvas>.
        frames_data = ["\n".join(frame) for frame in sequence.lines_per_frame]
    else:
        # Other styles: pre-convert to HTML spans, one string per frame.
        frames_data = [
            "\n".join(ansi_to_html(line) for line in frame)
            for frame in sequence.lines_per_frame
        ]

    frames_json = json.dumps(
        frames_data, ensure_ascii=False, separators=(",", ":"))
    audio_uri = "null"
    if audio_b64:
        audio_uri = json.dumps(
            f"data:{audio_mime or 'audio/mpeg'};base64,{audio_b64}")
    return _PLAYER_TEMPLATE.format(
        charset=html.escape(sequence.charset),
        w=sequence.width,
        h=sequence.height,
        n=len(sequence.lines_per_frame),
        frames=frames_json,
        interval=sequence.interval,
        is_blocks="true" if is_blocks else "false",
        audio_uri=audio_uri,
        audio_mime=json.dumps(audio_mime or "audio/mpeg"),
        pre_style="display:none" if is_blocks else "",
        canvas_style="" if is_blocks else "display:none",
    )
