"""Self-contained HTML player generator (PRD.md §5.6)."""

from __future__ import annotations

import html
import json

from termify.engine import FrameSequence


_PLAYER_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<title>Termify — {charset} animation</title>
<style>
  :root {{ --bg:#0a0e14; --fg:#c9d1d9; --accent:#58a6ff; }}
  body {{ margin:0; background:var(--bg); color:var(--fg);
          font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
          display:flex; flex-direction:column; align-items:center;
          min-height:100vh; padding:24px; box-sizing:border-box; }}
  h1 {{ font-size:14px; font-weight:600; letter-spacing:.05em; color:var(--accent); }}
  pre {{ background:#161b22; border:1px solid #30363d; border-radius:8px;
        padding:16px 20px; line-height:1.15; font-size:13px;
        overflow:auto; max-width:100%; white-space:pre; }}
  footer {{ margin-top:12px; font-size:11px; color:#6e7681; }}
</style>
</head>
<body>
  <h1>Termify · {charset} · {w}×{h} · {n} frames</h1>
  <pre id="screen"></pre>
  <footer>Generated by Termify — no external dependencies.</footer>
  <script>
    var FRAMES = {frames};
    var INTERVAL = {interval} * 1000; // ms
    var idx = 0;
    var el = document.getElementById('screen');
    function tick() {{
      el.textContent = FRAMES[idx].join('\n');
      idx = (idx + 1) % FRAMES.length;
    }}
    tick();
    setInterval(tick, INTERVAL);
  </script>
</body>
</html>
"""


def render(sequence: FrameSequence) -> str:
    """Generate a self-contained .html player page as a string."""
    frames_json = json.dumps(sequence.lines_per_frame, ensure_ascii=False, indent=2)
    return _PLAYER_TEMPLATE.format(
        charset=html.escape(sequence.charset),
        w=sequence.width,
        h=sequence.height,
        n=len(sequence.lines_per_frame),
        frames=frames_json,
        interval=sequence.interval,
    )
